# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AddPredictResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, message: str=None, predict_id: str=None):  # noqa: E501
        """AddPredictResponse - a model defined in Swagger

        :param code: The code of this AddPredictResponse.  # noqa: E501
        :type code: int
        :param message: The message of this AddPredictResponse.  # noqa: E501
        :type message: str
        :param predict_id: The predict_id of this AddPredictResponse.  # noqa: E501
        :type predict_id: str
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'predict_id': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'predict_id': 'predictId'
        }

        self._code = code
        self._message = message
        self._predict_id = predict_id

    @classmethod
    def from_dict(cls, dikt) -> 'AddPredictResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddPredictResponse of this AddPredictResponse.  # noqa: E501
        :rtype: AddPredictResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this AddPredictResponse.


        :return: The code of this AddPredictResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this AddPredictResponse.


        :param code: The code of this AddPredictResponse.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this AddPredictResponse.


        :return: The message of this AddPredictResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this AddPredictResponse.


        :param message: The message of this AddPredictResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def predict_id(self) -> str:
        """Gets the predict_id of this AddPredictResponse.


        :return: The predict_id of this AddPredictResponse.
        :rtype: str
        """
        return self._predict_id

    @predict_id.setter
    def predict_id(self, predict_id: str):
        """Sets the predict_id of this AddPredictResponse.


        :param predict_id: The predict_id of this AddPredictResponse.
        :type predict_id: str
        """

        self._predict_id = predict_id
