# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.predict_status_status_list import PredictStatusStatusList  # noqa: F401,E501
from swagger_server import util


class PredictStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status_list: List[PredictStatusStatusList]=None):  # noqa: E501
        """PredictStatus - a model defined in Swagger

        :param status_list: The status_list of this PredictStatus.  # noqa: E501
        :type status_list: List[PredictStatusStatusList]
        """
        self.swagger_types = {
            'status_list': List[PredictStatusStatusList]
        }

        self.attribute_map = {
            'status_list': 'status_list'
        }

        self._status_list = status_list

    @classmethod
    def from_dict(cls, dikt) -> 'PredictStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictStatus of this PredictStatus.  # noqa: E501
        :rtype: PredictStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status_list(self) -> List[PredictStatusStatusList]:
        """Gets the status_list of this PredictStatus.


        :return: The status_list of this PredictStatus.
        :rtype: List[PredictStatusStatusList]
        """
        return self._status_list

    @status_list.setter
    def status_list(self, status_list: List[PredictStatusStatusList]):
        """Sets the status_list of this PredictStatus.


        :param status_list: The status_list of this PredictStatus.
        :type status_list: List[PredictStatusStatusList]
        """

        self._status_list = status_list
