# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.train_status_status_list import TrainStatusStatusList  # noqa: F401,E501
from swagger_server import util


class TrainStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status_list: List[TrainStatusStatusList]=None):  # noqa: E501
        """TrainStatus - a model defined in Swagger

        :param status_list: The status_list of this TrainStatus.  # noqa: E501
        :type status_list: List[TrainStatusStatusList]
        """
        self.swagger_types = {
            'status_list': List[TrainStatusStatusList]
        }

        self.attribute_map = {
            'status_list': 'status_list'
        }

        self._status_list = status_list

    @classmethod
    def from_dict(cls, dikt) -> 'TrainStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainStatus of this TrainStatus.  # noqa: E501
        :rtype: TrainStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status_list(self) -> List[TrainStatusStatusList]:
        """Gets the status_list of this TrainStatus.


        :return: The status_list of this TrainStatus.
        :rtype: List[TrainStatusStatusList]
        """
        return self._status_list

    @status_list.setter
    def status_list(self, status_list: List[TrainStatusStatusList]):
        """Sets the status_list of this TrainStatus.


        :param status_list: The status_list of this TrainStatus.
        :type status_list: List[TrainStatusStatusList]
        """

        self._status_list = status_list
